/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package malaysiaherb;
import ClassAll.Plant;
import ClassAll.database;
import static ClassAll.database.getConnection;
import com.sun.jdi.connect.spi.Connection;

import java.awt.Image;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class MAIN_WINDOW extends javax.swing.JFrame{

    /**
     * Creates new form MAIN_WINDOW
     */
    public MAIN_WINDOW() {
        initComponents();
        ImageIcon backgroundimage = new ImageIcon ("src\\img\\home1.png");
        ImageIcon aboutphoto = new ImageIcon ("src\\img\\about.png");
        ImageIcon buy = new ImageIcon ("src\\img\\Buy Your Plant With Us.png");
       jLabel13.setIcon(backgroundimage);
       aboutlbl.setIcon(aboutphoto);
       buylbl.setIcon(buy);
       ClassAll.database.getConnection();
       
       selectedtable("");
       selectedtable2();
      Showplanttobuy(imageindex);
        

    }
   

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        mainwindowtab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        aboutlbl = new javax.swing.JLabel();
        jPanel1_browsepanel = new javax.swing.JPanel();
        jButton_previousplant = new javax.swing.JButton();
        jButton_nextplant = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_commonname = new javax.swing.JTextField();
        jTextField_scientificname = new javax.swing.JTextField();
        jLabel_plantimg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        plantusage_area = new javax.swing.JTextArea();
        showbutton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2_Plant = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_plantimg1buypage = new javax.swing.JLabel();
        jButton_previousplant1 = new javax.swing.JButton();
        jButton_nextplant2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_commonnamebuypage = new javax.swing.JTextField();
        jTextField_scientificnamebuypage = new javax.swing.JTextField();
        jLabel_priceLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablebuypage = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1Userlist = new javax.swing.JButton();
        buylbl = new javax.swing.JLabel();
        cloylbl = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Pk1 = new javax.swing.JRadioButton();
        Hb1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Hb2 = new javax.swing.JRadioButton();
        Pk2 = new javax.swing.JRadioButton();
        Hb3 = new javax.swing.JRadioButton();
        Pk3 = new javax.swing.JRadioButton();
        Hb4 = new javax.swing.JRadioButton();
        Pk6 = new javax.swing.JRadioButton();
        Pk5 = new javax.swing.JRadioButton();
        Hb5 = new javax.swing.JRadioButton();
        Hb6 = new javax.swing.JRadioButton();
        Pk4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Cloyster = new javax.swing.JLabel();
        Chandelure2 = new javax.swing.JLabel();
        Zingiber = new javax.swing.JLabel();
        Dhelmise = new javax.swing.JLabel();
        Somnifera = new javax.swing.JLabel();
        Chandelure5 = new javax.swing.JLabel();
        Chandelurelbl = new javax.swing.JLabel();
        Zingiberlbl = new javax.swing.JLabel();
        Ortholbl = new javax.swing.JLabel();
        Somniferalbl = new javax.swing.JLabel();
        Chelmiselbl = new javax.swing.JLabel();
        Cloysterlbl = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainwindowtab.setBackground(new java.awt.Color(0, 102, 51));
        mainwindowtab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainwindowtab.setForeground(new java.awt.Color(255, 255, 255));
        mainwindowtab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainwindowtab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainwindowtab.setName(""); // NOI18N
        mainwindowtab.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        jLabel13.setText("jLabel13");
        jLabel13.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        mainwindowtab.addTab("HOME", jPanel3);

        About.setBackground(new java.awt.Color(205, 232, 178));

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel2.setText("ABOUT  US");

        aboutlbl.setText("jLabel21");

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGroup(AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aboutlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mainwindowtab.addTab("ABOUT", About);

        jPanel1_browsepanel.setBackground(new java.awt.Color(205, 232, 178));

        jButton_previousplant.setBackground(new java.awt.Color(204, 204, 204));
        jButton_previousplant.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_previousplant.setText("<<<");
        jButton_previousplant.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_previousplant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_previousplantActionPerformed(evt);
            }
        });

        jButton_nextplant.setBackground(new java.awt.Color(204, 204, 204));
        jButton_nextplant.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_nextplant.setText(">>>");
        jButton_nextplant.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_nextplant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextplantActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 153, 51));
        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel1.setText("OUR HERBS:");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setText("Common Name:");

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setText("Scientific name:");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setText("Description:");

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel7.setText("Plant Usage:");

        jTextField_commonname.setEditable(false);
        jTextField_commonname.setBackground(new java.awt.Color(205, 232, 178));
        jTextField_commonname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField_commonname.setAutoscrolls(false);
        jTextField_commonname.setBorder(null);
        jTextField_commonname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_commonnameInputMethodTextChanged(evt);
            }
        });
        jTextField_commonname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_commonnameActionPerformed(evt);
            }
        });

        jTextField_scientificname.setEditable(false);
        jTextField_scientificname.setBackground(new java.awt.Color(205, 232, 178));
        jTextField_scientificname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField_scientificname.setBorder(null);

        jLabel_plantimg.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_plantimg.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel_plantimg.setMaximumSize(new java.awt.Dimension(360, 302));
        jLabel_plantimg.setMinimumSize(new java.awt.Dimension(360, 302));
        jLabel_plantimg.setPreferredSize(new java.awt.Dimension(360, 302));
        jLabel_plantimg.setVerifyInputWhenFocusTarget(false);

        desc_area.setEditable(false);
        desc_area.setBackground(new java.awt.Color(205, 232, 178));
        desc_area.setColumns(20);
        desc_area.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        desc_area.setRows(5);
        desc_area.setBorder(null);
        jScrollPane1.setViewportView(desc_area);

        plantusage_area.setEditable(false);
        plantusage_area.setBackground(new java.awt.Color(205, 232, 178));
        plantusage_area.setColumns(20);
        plantusage_area.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        plantusage_area.setRows(5);
        plantusage_area.setBorder(null);
        jScrollPane2.setViewportView(plantusage_area);

        showbutton.setBackground(new java.awt.Color(204, 204, 255));
        showbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showbutton.setText("Show Plant");
        showbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttonActionPerformed(evt);
            }
        });

        jTable2_Plant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2_Plant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Scientific Name", "Traditional Herbs"
            }
        ));
        jTable2_Plant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2_PlantMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable2_Plant);

        javax.swing.GroupLayout jPanel1_browsepanelLayout = new javax.swing.GroupLayout(jPanel1_browsepanel);
        jPanel1_browsepanel.setLayout(jPanel1_browsepanelLayout);
        jPanel1_browsepanelLayout.setHorizontalGroup(
            jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_scientificname, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                        .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_browsepanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_commonname, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel_plantimg, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_previousplant)
                        .addGap(44, 44, 44)
                        .addComponent(showbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton_nextplant)
                        .addGap(76, 76, 76)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel1_browsepanelLayout.setVerticalGroup(
            jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_plantimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_previousplant)
                            .addComponent(jButton_nextplant)))
                    .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1_browsepanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_commonname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1_browsepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField_scientificname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mainwindowtab.addTab("BROWSE", jPanel1_browsepanel);

        jPanel4.setBackground(new java.awt.Color(205, 232, 178));

        jLabel8.setBackground(new java.awt.Color(0, 153, 51));
        jLabel8.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel8.setText("BUY YOUR PLANTS");

        jLabel_plantimg1buypage.setBackground(new java.awt.Color(102, 255, 255));

        jButton_previousplant1.setBackground(new java.awt.Color(204, 204, 204));
        jButton_previousplant1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_previousplant1.setText("<<<");
        jButton_previousplant1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_previousplant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_previousplant1ActionPerformed(evt);
            }
        });

        jButton_nextplant2.setBackground(new java.awt.Color(204, 204, 204));
        jButton_nextplant2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_nextplant2.setText(">>>");
        jButton_nextplant2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_nextplant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextplant2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel9.setText("Common Name:");

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setText("Scientific name:");

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel11.setText("PRICE:");

        jTextField_commonnamebuypage.setEditable(false);
        jTextField_commonnamebuypage.setBackground(new java.awt.Color(205, 232, 178));
        jTextField_commonnamebuypage.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextField_commonnamebuypage.setAutoscrolls(false);
        jTextField_commonnamebuypage.setBorder(null);
        jTextField_commonnamebuypage.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_commonnamebuypageInputMethodTextChanged(evt);
            }
        });
        jTextField_commonnamebuypage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_commonnamebuypageActionPerformed(evt);
            }
        });

        jTextField_scientificnamebuypage.setEditable(false);
        jTextField_scientificnamebuypage.setBackground(new java.awt.Color(205, 232, 178));
        jTextField_scientificnamebuypage.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextField_scientificnamebuypage.setBorder(null);

        jLabel_priceLabel.setBackground(new java.awt.Color(255, 51, 51));
        jLabel_priceLabel.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        jLabel_priceLabel.setForeground(new java.awt.Color(255, 255, 51));
        jLabel_priceLabel.setOpaque(true);

        jTablebuypage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Scientific Name", "Traditional Herbs"
            }
        ));
        jTablebuypage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablebuypageMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTablebuypage);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Herbs and Plants List");

        jLabel12.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        jLabel12.setText("RM");

        jButton1Userlist.setBackground(new java.awt.Color(204, 204, 204));
        jButton1Userlist.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton1Userlist.setText("List User");
        jButton1Userlist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1Userlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1UserlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1Userlist, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(buylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton_previousplant1)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(238, 238, 238)
                                        .addComponent(jButton_nextplant2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel_priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField_scientificnamebuypage, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                            .addComponent(jTextField_commonnamebuypage))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_plantimg1buypage, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(75, 75, 75))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(37, 37, 37)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_plantimg1buypage, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton_previousplant1)
                                            .addComponent(jButton_nextplant2))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jTextField_commonnamebuypage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jTextField_scientificnamebuypage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel_priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12))))
                        .addGap(32, 32, 32)))
                .addComponent(jButton1Userlist)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        mainwindowtab.addTab("BUY", jPanel4);

        cloylbl.setBackground(new java.awt.Color(205, 232, 178));
        cloylbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel14.setBackground(new java.awt.Color(0, 153, 51));
        jLabel14.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabel14.setText("IS IT PLANT OR IS IT POKEMON?");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("1. Chandelure");

        buttonGroup1.add(Pk1);
        Pk1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pk1.setText("Pokemon");
        Pk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pk1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Hb1);
        Hb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hb1.setText("Herb");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(Hb2);
        Hb2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hb2.setText("Herb");
        Hb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hb2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(Pk2);
        Pk2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pk2.setText("Pokemon");
        Pk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pk2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(Hb3);
        Hb3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hb3.setText("Herb");
        Hb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hb3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(Pk3);
        Pk3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pk3.setText("Pokemon");
        Pk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pk3ActionPerformed(evt);
            }
        });

        buttonGroup4.add(Hb4);
        Hb4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hb4.setText("Pokemon");
        Hb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hb4ActionPerformed(evt);
            }
        });

        buttonGroup6.add(Pk6);
        Pk6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pk6.setText("Pokemon");
        Pk6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pk6ActionPerformed(evt);
            }
        });

        buttonGroup5.add(Pk5);
        Pk5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pk5.setText("Pokemon");
        Pk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pk5ActionPerformed(evt);
            }
        });

        buttonGroup5.add(Hb5);
        Hb5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hb5.setText("Herb");
        Hb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hb5ActionPerformed(evt);
            }
        });

        buttonGroup6.add(Hb6);
        Hb6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hb6.setText("Herb");
        Hb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hb6ActionPerformed(evt);
            }
        });

        buttonGroup4.add(Pk4);
        Pk4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pk4.setText("Herb");
        Pk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pk4ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("2. Orthosiphon");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("3. Zingiber ");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("4. Cloyster");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("6. Somnifera ");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("5. Dhelmise");

        Cloyster.setBackground(new java.awt.Color(205, 232, 178));
        Cloyster.setOpaque(true);

        Chandelure2.setBackground(new java.awt.Color(205, 232, 178));
        Chandelure2.setOpaque(true);

        Zingiber.setBackground(new java.awt.Color(205, 232, 178));
        Zingiber.setOpaque(true);

        Dhelmise.setBackground(new java.awt.Color(205, 232, 178));
        Dhelmise.setOpaque(true);

        Somnifera.setBackground(new java.awt.Color(205, 232, 178));
        Somnifera.setOpaque(true);

        Chandelure5.setBackground(new java.awt.Color(205, 232, 178));
        Chandelure5.setOpaque(true);

        Chandelurelbl.setText(" ");

        Zingiberlbl.setText(" ");

        Ortholbl.setText(" ");

        Somniferalbl.setText(" ");

        Chelmiselbl.setText(" ");

        Cloysterlbl.setText(" ");

        javax.swing.GroupLayout cloylblLayout = new javax.swing.GroupLayout(cloylbl);
        cloylbl.setLayout(cloylblLayout);
        cloylblLayout.setHorizontalGroup(
            cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cloylblLayout.createSequentialGroup()
                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cloylblLayout.createSequentialGroup()
                                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pk1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hb1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hb2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cloylblLayout.createSequentialGroup()
                                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Pk2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(156, 156, 156)
                                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(jButton3)
                                            .addComponent(jButton2))))
                                .addGap(42, 42, 42)
                                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Zingiber, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chandelure2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chandelure5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chandelurelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Zingiberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ortholbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Hb3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pk3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Hb4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Pk6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cloylblLayout.createSequentialGroup()
                                    .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cloylblLayout.createSequentialGroup()
                                            .addComponent(Pk4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(cloylblLayout.createSequentialGroup()
                                            .addGap(0, 2, Short.MAX_VALUE)
                                            .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(cloylblLayout.createSequentialGroup()
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(32, 32, 32)
                                                    .addComponent(jButton4))
                                                .addGroup(cloylblLayout.createSequentialGroup()
                                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(38, 38, 38)
                                                    .addComponent(jButton5))))
                                        .addGroup(cloylblLayout.createSequentialGroup()
                                            .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(cloylblLayout.createSequentialGroup()
                                                    .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Pk5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Hb5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cloylblLayout.createSequentialGroup()
                                                    .addComponent(Hb6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(110, 110, 110)))
                                    .addGap(9, 9, 9)))
                            .addGroup(cloylblLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButton6)))))
                .addGap(65, 65, 65)
                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chelmiselbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dhelmise, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cloyster, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Somnifera, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Somniferalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cloysterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        cloylblLayout.setVerticalGroup(
            cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cloylblLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Chandelurelbl)
                .addGap(10, 10, 10)
                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Cloyster, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(Chelmiselbl))
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Hb1)
                                .addComponent(Chandelure2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cloylblLayout.createSequentialGroup()
                                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pk1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(Ortholbl)
                        .addGap(12, 12, 12)))
                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Chandelure5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dhelmise, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(Somniferalbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Somnifera, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cloylblLayout.createSequentialGroup()
                                .addComponent(Zingiberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Zingiber, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(cloylblLayout.createSequentialGroup()
                                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cloylblLayout.createSequentialGroup()
                                        .addComponent(Hb5)
                                        .addGap(18, 18, 18)
                                        .addComponent(Pk5))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(cloylblLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Cloysterlbl)
                .addGap(49, 49, 49)
                .addComponent(Pk4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hb4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jButton3))
                        .addGap(24, 24, 24)
                        .addComponent(Pk2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pk3)
                        .addGap(18, 18, 18)
                        .addComponent(Hb3))
                    .addGroup(cloylblLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(cloylblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pk6)
                        .addGap(18, 18, 18)
                        .addComponent(Hb6)))
                .addGap(68, 68, 68))
        );

        mainwindowtab.addTab("GAME", cloylbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainwindowtab, javax.swing.GroupLayout.PREFERRED_SIZE, 1292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainwindowtab, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    String ImgPath=null;
    int imageindex=0;
    public ImageIcon ResizeImg(String imgpath, byte[] plantimg)
{
   ImageIcon image=null;
   

    if (imgpath !=null)
    {
        image = new ImageIcon(imgpath);

    }
    else {
        image = new ImageIcon(plantimg);
    }
    Image img = image.getImage();
    Image img2 = img.getScaledInstance(jLabel_plantimg.getWidth(),jLabel_plantimg.getHeight(), jLabel_plantimg.getWidth());
    ImageIcon imagenow= new ImageIcon(img2);
    return image;
}
    
   public ArrayList<Plant> getPlantList(String plantname) {
    ArrayList<Plant> plantlist = new ArrayList<>();
    //connect = database.getConnection();
    PreparedStatement input = null;
    ResultSet rs = null;
    
    try {
        input = ClassAll.database.getConnection().prepareStatement("SELECT `ID`,`Name`, `Scientific_name`, `Description`, `Plant_Usage`, `Plant_type`, `Plant_Image`,`Price` FROM `plants`");
        
        rs = input.executeQuery();
        
        while (rs.next()) {
            Plant plant = new Plant(
                rs.getInt("id"),
                rs.getString("Name"),
                rs.getString("Scientific_name"),
                rs.getString("Description"),
                rs.getString("Plant_Usage"),
                rs.getString("plant_type"),
                rs.getBytes("plant_image"),
                rs.getDouble("Price")
            );
            plantlist.add(plant);
        }
    } catch (SQLException ex) {
        Logger.getLogger(MAIN_WINDOW.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        // Close resources in finally block
        if (rs != null) {
            try {
                rs.close();
            } catch (SQLException e) {
                Logger.getLogger(MAIN_WINDOW.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        if (input != null) {
            try {
                input.close();
            } catch (SQLException e) {
                Logger.getLogger(MAIN_WINDOW.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }
    return plantlist;
}

   
    public void Showplant(int index) {
   ArrayList<Plant> showplant = getPlantList("");
  
    if (index >= 0 && index < showplant.size()) {
        Plant plant = showplant.get(index);
        jTextField_commonname.setText(plant.getName());
        jTextField_scientificname.setText(plant.getSN());
        desc_area.setText(plant.getDesc());
        desc_area.setLineWrap(true); // Enable line wrap
        desc_area.setWrapStyleWord(true); // Enable word wrap
        desc_area.setEditable(false);
        plantusage_area.setText(plant.getPS());
        plantusage_area.setLineWrap(true); // Enable line wrap
        plantusage_area.setWrapStyleWord(true); // Enable word wrap
        plantusage_area.setEditable(false);
        jLabel_plantimg.setIcon(ResizeImg(null, plant.getImage()));
        jTextField_commonname.setEditable(false);
        jTextField_scientificname.setEditable(false);
    } else {
        // Handle out of bounds index
        System.out.println("Index out of bounds");
    }
}
    
    public void Showplanttobuy (int index) {
   ArrayList<Plant> showplant = getPlantList("");
    if (index >= 0 && index < showplant.size()) {
        Plant plant = showplant.get(index);
        jTextField_commonnamebuypage.setText(plant.getName());
        jTextField_scientificnamebuypage.setText(plant.getSN());
        jLabel_priceLabel.setText(Double.toString(plant.getPrice()));
        jLabel_plantimg1buypage.setIcon(ResizeImg(null, plant.getImage()));
        jTextField_commonname.setEditable(false);
        jTextField_scientificname.setEditable(false);
    } else {
        // Handle out of bounds index
        System.out.println("Index out of bounds");
    }
    
}
    
    
public void selectedtable(String plant)
{  
    DefaultTableModel table = (DefaultTableModel) jTable2_Plant.getModel();
    table.setRowCount(0);
    ClassAll.Plant plantname= new ClassAll.Plant();
    ArrayList<Plant> plant_list = getPlantList(plant);
    for (int i = 0; i < plant_list.size(); i++) {
        Object[] row = new Object[4];
        row[0] = plant_list.get(i).getId();
        row[1] = plant_list.get(i).getName();
        row[2] = plant_list.get(i).getSN();
        row[3] =plant_list.get(i).getPT();
        // Add the rest of the columns if needed
        table.addRow(row);
    }
}

public void selectedtable2()
{
    
    
       ArrayList<Plant> plant_list = getPlantList("");
    DefaultTableModel table = (DefaultTableModel) jTablebuypage.getModel();
    
    for (Plant plant : plant_list) {
        Object[] row = new Object[4];
        row[0] = plant.getId();
        row[1] = plant.getName();
        row[2] = plant.getSN();
        row[3] = plant.getPT();
        // Add the rest of the columns if needed
        table.addRow(row);
    }


}
    
    private void jTextField_commonnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_commonnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_commonnameActionPerformed

    private void jButton_nextplantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextplantActionPerformed
        // TODO add your handling code here:
        imageindex++;
        if(imageindex >=getPlantList("").size())
        {
            imageindex =getPlantList("").size()-1;
        }
        Showplant(imageindex);
    }//GEN-LAST:event_jButton_nextplantActionPerformed

    private void jButton_previousplantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_previousplantActionPerformed
        // TODO add your handling code here:
        imageindex--;
        if (imageindex < 0)
        {
            imageindex=0;
        }
        Showplant(imageindex);
        
    }//GEN-LAST:event_jButton_previousplantActionPerformed

    private void jTextField_commonnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_commonnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_commonnameInputMethodTextChanged

    private void showbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttonActionPerformed
        // TODO add your handling code here:
       imageindex=0;
       Showplant(imageindex);
    }//GEN-LAST:event_showbuttonActionPerformed

    private void jTable2_PlantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2_PlantMouseClicked
        // TODO add your handling code here:
        int index = jTable2_Plant.getSelectedRow();
        Showplant(index);
    }//GEN-LAST:event_jTable2_PlantMouseClicked

    private void jButton_previousplant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_previousplant1ActionPerformed
        // TODO add your handling code here:
        imageindex--;
        if (imageindex < 0)
        {
            imageindex=0;
        }
        Showplanttobuy(imageindex);
    }//GEN-LAST:event_jButton_previousplant1ActionPerformed

    private void jButton_nextplant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextplant2ActionPerformed
        // TODO add your handling code here:
        imageindex++;
        if(imageindex >=getPlantList("").size())
        {
            imageindex =getPlantList("").size()-1;
        }
        Showplanttobuy(imageindex);
    }//GEN-LAST:event_jButton_nextplant2ActionPerformed

    private void jTextField_commonnamebuypageInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_commonnamebuypageInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_commonnamebuypageInputMethodTextChanged

    private void jTextField_commonnamebuypageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_commonnamebuypageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_commonnamebuypageActionPerformed

    private void jTablebuypageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablebuypageMouseClicked
        // TODO add your handling code here:
        int index = jTablebuypage.getSelectedRow();
        Showplanttobuy(index);
    }//GEN-LAST:event_jTablebuypageMouseClicked

    private void jButton1UserlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1UserlistActionPerformed
        // TODO add your handling code here:
        Userlist userlist = new Userlist();
        userlist.setVisible(true);
        userlist.pack();
        userlist.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1UserlistActionPerformed

    private void Pk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pk4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pk4ActionPerformed

    private void Hb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hb6ActionPerformed

    private void Hb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hb5ActionPerformed

    private void Pk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pk5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pk5ActionPerformed

    private void Pk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pk6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pk6ActionPerformed

    private void Hb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hb4ActionPerformed

    private void Pk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pk3ActionPerformed

    private void Hb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hb3ActionPerformed

    private void Pk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pk2ActionPerformed

    private void Hb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hb2ActionPerformed

    private void Pk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pk1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImageIcon Chandelurepic =new ImageIcon ("src\\img\\Chandelure.png");
        if (Pk1.isSelected())
        {
            Chandelurelbl.setText("Correct!!");
        }
        else 
        {
            Chandelurelbl.setText("Wrong!!");
            
        }
        Chandelure2.setIcon(Chandelurepic);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         ImageIcon misaikucing =new ImageIcon ("src\\img\\Misai Kucing.jpg");
        if (Hb2.isSelected())
        {
            Ortholbl.setText("Correct!!");
        }
        else 
        {
            Ortholbl.setText("Wrong!!");
            
        }
        Chandelure5.setIcon(misaikucing);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ImageIcon lempoyang =new ImageIcon ("src\\img\\lempoyang.jpg");
        if (Hb3.isSelected())
        {
            Zingiberlbl.setText("Correct!!");
        }
        else 
        {
            Zingiberlbl.setText("Wrong!!");
            
        }
        Zingiber.setIcon(lempoyang);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         ImageIcon cloyster =new ImageIcon ("src\\img\\Cloyster.png");
        if (Hb4.isSelected())
        {
            Cloysterlbl.setText("Correct!!");
        }
        else 
        {
            Cloysterlbl.setText("Wrong!!");
            
        }
        Cloyster.setIcon(cloyster);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         ImageIcon dhelmise =new ImageIcon ("src\\img\\Dhelmise.png");
        if (Pk5.isSelected())
        {
            Chelmiselbl.setText("Correct!!");
        }
        else 
        {
            Chelmiselbl.setText("Wrong!!");
            
        }
        Dhelmise.setIcon(dhelmise);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ImageIcon somni =new ImageIcon ("src\\img\\Ashwaganda.jpg");
        if (Hb6.isSelected())
        {
            Somniferalbl.setText("Correct!!");
        }
        else 
        {
            Somniferalbl.setText("Wrong!!");
            
        }
        Somnifera.setIcon(somni);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JLabel Chandelure2;
    private javax.swing.JLabel Chandelure5;
    private javax.swing.JLabel Chandelurelbl;
    private javax.swing.JLabel Chelmiselbl;
    private javax.swing.JLabel Cloyster;
    private javax.swing.JLabel Cloysterlbl;
    private javax.swing.JLabel Dhelmise;
    private javax.swing.JRadioButton Hb1;
    private javax.swing.JRadioButton Hb2;
    private javax.swing.JRadioButton Hb3;
    private javax.swing.JRadioButton Hb4;
    private javax.swing.JRadioButton Hb5;
    private javax.swing.JRadioButton Hb6;
    private javax.swing.JLabel Ortholbl;
    private javax.swing.JRadioButton Pk1;
    private javax.swing.JRadioButton Pk2;
    private javax.swing.JRadioButton Pk3;
    private javax.swing.JRadioButton Pk4;
    private javax.swing.JRadioButton Pk5;
    private javax.swing.JRadioButton Pk6;
    private javax.swing.JLabel Somnifera;
    private javax.swing.JLabel Somniferalbl;
    private javax.swing.JLabel Zingiber;
    private javax.swing.JLabel Zingiberlbl;
    private javax.swing.JLabel aboutlbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel buylbl;
    private javax.swing.JPanel cloylbl;
    private javax.swing.JTextArea desc_area;
    private javax.swing.JButton jButton1;
    protected javax.swing.JButton jButton1Userlist;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_nextplant;
    private javax.swing.JButton jButton_nextplant2;
    private javax.swing.JButton jButton_previousplant;
    private javax.swing.JButton jButton_previousplant1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_plantimg;
    private javax.swing.JLabel jLabel_plantimg1buypage;
    private javax.swing.JLabel jLabel_priceLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1_browsepanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable2_Plant;
    private javax.swing.JTable jTablebuypage;
    javax.swing.JTextField jTextField_commonname;
    javax.swing.JTextField jTextField_commonnamebuypage;
    private javax.swing.JTextField jTextField_scientificname;
    private javax.swing.JTextField jTextField_scientificnamebuypage;
    private javax.swing.JTabbedPane mainwindowtab;
    private javax.swing.JTextArea plantusage_area;
    private javax.swing.JButton showbutton;
    // End of variables declaration//GEN-END:variables
}
